---
- name: "Ubuntu-nginx-site from Git"
  become: yes
  hosts: ubuntu
  vars_files:
    - nginx.vars
    - secret.vars
  tasks:
    - name: "Installing Nginx and php8.1-fpm"
      apt:
        name: 
          - nginx
          - git 
          - php8.1-fpm
          - php8.1
        state: present
        update_cache: yes
      notify:
        - restart/enable-nginx-php8.1-fpm

    - name: "Creating Document root /var/www/{{ domain_name }}"
      file:
        group: "{{ nginx_group }}"
        owner: "{{ nginx_user }}"
        path: "/var/www/{{ domain_name }}"
        state: directory

    - name: "Creating nginx conf /etc/nginx/sites-available/{{ domain_name }}.conf"
      template:
        dest: "/etc/nginx/sites-available/{{ domain_name }}.conf"
        src: vhost.tmpl
      notify:
        - restart/enable-nginx-php8.1-fpm

    - name: "Enabling nginx conf /etc/nginx/sites-available/{{ domain_name }}.conf"
      file:
        src: "/etc/nginx/sites-available/{{ domain_name }}.conf"
        state: link
        path: "/etc/nginx/sites-enabled/{{ domain_name }}.conf"
      notify:
        - restart/enable-nginx-php8.1-fpm
        
        
    - name: "cloning from Git"
      git:
        dest: "{{ git_dir }}"
        repo: "{{ git_url }}"
      register: git_status

    - name: "Copying content to document root /var/www/{{ domain_name }}"
      when: git_status.changed == true
      copy:
        src: "{{ git_dir }}"
        dest: "/var/www/{{ domain_name }}"
        owner: "{{ nginx_user }}"
        group: "{{ nginx_group }}"
        remote_src: yes 
      notify:
        - restart/enable-nginx-php8.1-fpm 
     
        
        
        
  handlers:
    - name: "restart/enable-nginx-php8.1-fpm"
      service:
        name: "{{ item }}"
        enabled: yes
        state: restarted
      with_items:
        - nginx
        - php8.1-fpm
